import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'home': 'Home',
          'changeLang': 'Change Language',
          'firstButton': 'Add Student',
          'secondButton': "Student List",
          'thirdButton': 'Material List',
          'fourthButton': "Assign Page",
          'fifthButton': "Returned Assignments",
          'chooseLang': "Choose Language",
          'studentName': "Student Name",
          'studentSurname': "Student Surname",
          'studentNumber': "Student Number",
          'studentClass': "Student Class",
          'studentBranch': "Student Branch",
          'fillBoxError': 'Please fill out the box',
          'addButton': 'Add',
          'savedMessage': 'Saved',
          'errorMessage': 'An error occured',
          'studentList': 'Student List',
          'deletedMessage': 'Deleted',
          'deleteQuestion': 'Delete?',
          'confirmation': 'Confirmation',
          'retrieveDeleteQuestion':
              'Are you sure you want to delete this assignment?',
          'deleteDescriptionQuestion': 'Do you really want to delete student named',
          'yes': 'Yes',
          'no': 'No',
          'noStudentError': 'There is no student',
          'materialSelect': 'Material Select',
          'error': 'Error',
          'numberPage': 'Number Page',
          'inputValue': 'Input a value',
          'inputValueError': 'Please input a value',
          'assignButton': 'Assign',
          'assignedMessage': 'Material assigned to the student',
          'materialInventory': 'Material Inventory',
          'assignedPage': 'Assigned Student Page',
          'retrievePart': 'Retrieve Part',
          'normal': 'Normal',
          'broken': 'Broken',
          'retrieve': 'Retrieve',
          'retrievedMessage': 'Retrieved',
          'Arduino': 'Arduino',
          'Breadboard': 'Breadboard',
          'LED': 'LED',
          '220 Ohm Resistor': '220 Ohm Resistor',
          'Connection Cables': 'Connection Cables',
          'Switch': 'Switch',
          '10K Ohm Resistor': '10K Ohm Resistor',
          'Potentiometer': 'Potentiometer',
          'Voltmeter': 'Voltmeter',
          'LDR': 'LDR',
          'Common Cathode LED': 'Common Cathode LED',
          'Resistor': 'Resistor',
          'Active Buzzer': 'Active Buzzer',
          'Button': 'Button',
          'Common Cathode Display': 'Common Cathode Display',
          'IR Receiver': 'IR Receiver',
          'IR Transmitter Remote Control': 'IR Transmitter Remote Control',
          'Ultrasonic Distance Sensor': 'Ultrasonic Distance Sensor',
          'LCD Display': 'LCD Display',
          'Temperature Sensor': 'Temperature Sensor',
          'Distance Sensor': 'Distance Sensor',
          'Normal': 'Normal',
          'Broken': 'Broken',
          'Credit': 'Made by Ibrahim Yasin Goktas',
          'searchBar': 'Search',
        },
        'tr_TR': {
          'home': 'Ana Sayfa',
          'changeLang': 'Dil Değiştir',
          'firstButton': 'Öğrenci Ekle',
          'secondButton': "Öğrenci Listesi",
          'thirdButton': 'Parça Listesi',
          'fourthButton': "Tanımlılar Listesi",
          'fifthButton': "Geri Alınanlar Listesi",
          'chooseLang': 'Dil Seç',
          'studentName': "Öğrenci Adı",
          'studentSurname': "Öğrenci Soyadı",
          'studentNumber': "Öğrenci Numarası",
          'studentClass': "Öğrenci Sınıfı",
          'studentBranch': "Öğrenci Şubesi",
          'fillBoxError': 'Lütfen kutucuğu boş bırakmayınız',
          'addButton': 'Ekle',
          'savedMessage': 'Kaydedildi',
          'errorMessage': 'Bir hata oluştu',
          'studentList': 'Öğrenci Listesi',
          'yes': 'Evet',
          'no': 'Hayır',
          'deletedMessage': 'Silindi',
          'deleteQuestion': 'Sil?',
          'confirmation': 'Onay',
          'retrieveDeleteQuestion':
              'Bu tanımlamayı silmek istediğinizden emin misiniz?',
          'deleteDescriptionQuestion': 'Bu öğrenciyi silmek istiyor musunuz:',
          'noStudentError': 'Hiç öğrenci yok',
          'materialSelect': 'Parça Seç',
          'error': 'Hata',
          'numberPage': 'Parça Sayısı',
          'inputValue': 'Bir değer giriniz',
          'inputValueError': 'Lütfen bir değer giriniz',
          'assignButton': 'Tanımla',
          'assignedMessage': 'Parça öğrenciye tanımlandı',
          'materialInventory': 'Parça Envanteri',
          'retrievePart': 'Parçayı Geri Al',
          'normal': 'Sağlam',
          'broken': 'Kırık',
          'retrieve': 'Geri Al',
          'retrievedMessage': 'Geri Alındı',
          'Arduino': 'Arduino',
          'Breadboard': 'Breadboard',
          'LED': 'LED',
          '220 Ohm Resistor': '220 Ohm Direnç',
          'Connection Cables': 'Bağlantı Kabloları',
          'Switch': 'Anahtar',
          '10K Ohm Resistor': '10K OHM direnç',
          'Potentiometer': 'Potansiyometre',
          'Voltmeter': 'Voltmetre',
          'LDR': 'LDR',
          'Common Cathode LED': 'Ortak Katot LED',
          'Resistor': 'Direnç',
          'Active Buzzer': 'Aktif Buzzer',
          'Button': 'Buton',
          'Common Cathode Display': 'Ortak Katot Display',
          'IR Receiver': 'IR Alıcı',
          'IR Transmitter Remote Control': 'IR Verici Kumanda',
          'Ultrasonic Distance Sensor': 'Ultrasonik Mesafe Sensörü',
          'LCD Display': 'LCD Display',
          'Temperature Sensor': 'Sıcaklık Sensörü',
          'Distance Sensor': 'Mesafe Sensörü',
          'Normal': 'Sağlam',
          'Broken': 'Kırık',
          'Credit': 'İbrahim Yasin Göktaş tarafından yapıldı',
          'searchBar': 'Filtrele',
        }
      };
}
